### ISSUE TITLE
deferToThread() usable with inline callbacks?

### ISSUE THREAD

**Issue by LaPriWa** [cocagne/txdbus#39]
I exported two object with one blocking method each. I would like to use the threads.deferToThread() method from twisted, in order to make the blocking methods non-blocking. I don't understand, how to use this method together with inline callbacks. Does a solution for this problem exist?

**Comment by cocagne** [comment]
That should work fine. Odds are you're over complicating it (which is easy
to do). The following should work just fine:

@defer.inlineCallbacks
def doBlockingThing():
    blocking_result = yield threads.deferToThread(blockingFunction)
    defer.returnValue(blocking_result)

All deferToThread does is return a Deferred to the eventual result of
blockingFunction. You can use it just like any other Deferred; it's not
special in any way.  Please note, however, that you have to pass the
function object to deferToThread. An easy mistake is to accidentally call
the function rather than pass it for execution. So make sure you're not
doing this by accident: deferToThread(blockingFunction*()*)

Tom
