### ISSUE TITLE
Create a new release on PyPI: 1.1.0

### ISSUE THREAD

**Issue by exvito** [cocagne/txdbus#64]
Latest release on PyPI is lacking the latest improvements, including Python 3 support and support for UNIX_FD function/method arguments, probably among others.

See https://github.com/cocagne/txdbus/issues/11#issuecomment-306437799 and https://github.com/cocagne/txdbus/issues/24#issuecomment-306362610.

Per those discussions, this should move forward once #61 is fixed which, in turn, declares #11 ready for release -- for the time being. :)

Not sure about the release numbering policy, any pointers?

**Comment by cocagne** [comment]
Python3 is a major step forward in terms of functionality but it's fully
backwards-compatible from an API perspective so that would suggest a bump
in the minor version number. That'd put the next release at 1.1.0 I think.

**Comment by exvito** [comment]
@cocagne, agreed, 1.1.0 would be next, per a semver approach.

I have no experience at all in publishing to PyPI even though I could take a stab at updating `setup.py`... Would you agree that it would be valuable to ship wheels to PyPI, as well? If so, do you know how to attain that?

**Comment by hobarrera** [comment]
`python setup.py bdist_wheel sdist upload` will generate wheels, sourceballs, and upload both. I recommend running `git clean -xdf` first, to make sure nothing extra is included in them.

I really like `setuptools_scm` -- instead of coding the version into `setup.py`, it reads the version for the git tag. It also shows correct version for builds done from untagged commits (eg: dev builds), like, for example `1.1.0.post16+gbf6e93a` (this is a standard python format too).

I generally use travis to auto-deploy tags to PyPI (combined with `setuptools_scm`. If @cocagne is okay with that I can configure it here (you'd need to put your PyPI password on the travis UI, so it's really your call).

**Comment by cocagne** [comment]
I'd rather not put my PyPI password into an external database. As recent
news events highlight, those databases get hacked all the time and I
maintain the pysrp library under the same account. Someone uploading a
malicious version of that library could be *really* bad news. Despite the
amazing flurry of activity you guys have generated, I expect that the
update rate will remain infrequent enough that I can continue with a manual
update process.

With respect to wheels, what do they offer beyond sdist? I haven't looked
into the Python packaging process for several years now so I'm a bit out of
date on that front.

Tom

**Comment by exvito** [comment]
Quoting http://pythonwheels.com, Advantages of wheels:

> 1. Faster installation for pure python and native C extension packages.
> 2. Avoids arbitrary code execution for installation. (Avoids setup.py)
> 3. Installation of a C extension does not require a compiler on Windows or macOS.
> 4. Allows better caching for testing and continuous integration.
> 5. Creates .pyc files as part of installation to ensure they match the python interpreter used.
> 6. More consistent installs across platforms and machines.

In txdbus' case, point 3. is irrelevant given that the code is Python only. That means that a universal wheel can be shipped (mostly like an sdist, but the the above mentioned benefits). :)

**Comment by cocagne** [comment]
Ahhh. Okay, I knew about the C extensions but missed the other benefits.
I'm sold on uploading wheels as well.

**Comment by cocagne** [comment]
Okay, so between going on vacation and craziness at the office, I've lost
track. Are we ready for the next release or does essential work yet remain?

Tom

**Comment by exvito** [comment]
Tom, thanks for following up.

I've been checking my txdbus "dependent" projects, mostly doing bluetooth under Python 3 on a raspberry pi, and they seem to be working as expected with the current master. There are a few more left. I expect I'll have that confirmation before the end of the week.

After that, I'll review the overall status and share my 2c. on whether I think we're ready for that or not.

**Comment by cocagne** [comment]
Sounds good. Thanks Exvito

On Jul 5, 2017 11:28 AM, "exvito" <notifications@github.com> wrote:

Tom, thanks for following up.

I've been checking my txdbus "dependent" projects, mostly doing bluetooth
under Python 3 on a raspberry pi, and they seem to be working as expected
with the current master. There are a few more left. I expect I'll have that
confirmation before the end of the week.

After that, I'll review the overall status and share my 2c. on whether I
think we're ready for that or not.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cocagne/txdbus/issues/64#issuecomment-313155216>, or mute
the thread

**Comment by hobarrera** [comment]
Thanks for the followup! I've slowed down contributions quite a bit mostly because I feel `txdbus` is "mature enough", and has honestly been working great for my usages.

I will try and round back to pending issues eventually though. :)

**Comment by exvito** [comment]
Here's my take on this after an overall review:
* All my projects work with Python 3 with current master -- this is what "concerns me".
* Most issues identified in #11 are either addressed or have an open issue.
* The exception might be Python 3 marshalling/unmarshalling of ints for which I just created issue #73.

What I propose:
* Let's close #62, given that it is identified and has a proposed fix. It would be somewhat "silly" to ship a revision with clearly wrong code (if it's operation is not 100% understood).
* After that I say we should ship 1.1.0 where the release notes say "preliminary Python 3 support" or some equivalent wording (may need to pinpoint a particular 3.x version, I'm not certain the current code runs on 3.3, for example... ideas?)
* Let's get the code out there. This is the best way to get feedback: if it breaks for some existing projects, it means current testing is probably incomplete, given that all tests are passing under Python 2 and 3.

My next steps:
* I'll create a PR for #62, based on the analysis there and wait your review/merge.

**Comment by exvito** [comment]
#62 is closed now. I'm well versed in packaging to PyPI, @cocagne + @hobarrera can you help move this towards releasing 1.1.0 with updated version, wheels, sdist and release notes?

PS: Are there any release notes, by the way? If not, how should they be included? Suggestions welcome. :)

**Comment by hobarrera** [comment]
There's no changelog, or release notes for previous versions. TBH, I'd would include a `CHANGELOG.rst` file in the root of the repository, and include user-relevant changes there (it's good practice to keep it updated in future too).

Regarding version, we just need to push the version in `setup.py`.

Finally, pushing to PyPI is just:

```sh
git stash  # get uncommited changes out of the way
git clean -xdf  # remove anything hanging around to avoid it getting packaged
python setup.py sdist bdist_wheel upload
```

This last bit needs to be done by @cocagne though, since he's the owner on PyPI.

**Comment by exvito** [comment]
@cocagne, @hobarrera,

I just created PR #75 to move this forward. Your review is very welcome and, if ok, please go ahead and merge + publish.

Thanks.

**Comment by exvito** [comment]
@cocagne, thanks for merging #75.

The following URLs are still showing 1.0.14:
- https://pypi.org/project/txdbus/
- https://pypi.python.org/pypi/txdbus

...so I guess you haven't pushed the release to PyPI yet, is that correct or is there some kind of caching going on?

**Comment by hobarrera** [comment]
@exvito That's because the package still needs to be pushed to PyPI: https://github.com/cocagne/txdbus/issues/64#issuecomment-314927540

**Comment by cocagne** [comment]
Right, I wasn't able to push the changes to PyPI when I did the merge. They
should be there now though. Recent changes on the PyPI server broke my
local configuration but I think I got it all sorted out. Let me know if it
looks like something went wrong.

**Comment by exvito** [comment]
Looks like something is not 100% with the wheel as it is Python 2 only, for some reason:

- txdbus' file is `txdbus-1.1.0-py2-none-any.whl`.
- requests', for example is `requests-2.18.1-py2.py3-none-any.whl

Like I said before, I'm not versed in publishing to PyPI so, two questions:
- How to "generate" Python 2 and 3 wheel, like the one for requests, above?
- Can txdbus entry on PyPI be fixed without bumping the version?

**Comment by hobarrera** [comment]
Yes, the entry can be fixed by pushing a new version. Sorry, most of the projects I contribute to tend to be python3-only, so I forgot about that.

We need to add this to `setup.cfg`:
```ini
[bdist_wheel]
universal = 1
```

You can generate a new wheel and push it without bumping the version, AFAIK. It'll be a universal one (py2/py3), so we're okay in future.

**Comment by cocagne** [comment]
Looks like that did the trick. Thanks again for all your efforts Hugo &
Exvito!

Tom

**Comment by hobarrera** [comment]
Thank you! 🎉

**Comment by hobarrera** [comment]
Okay to close this? 🙂

**Comment by cocagne** [comment]
Yep :)

**Comment by exvito** [comment]
@cocagne, I don't mean to nitpick, but there are now two somewhat "confusing" published artifacts: the Python 2 wheel and the universal wheel. If possible, I would unpublished the Python 2 only one. :)

**Comment by cocagne** [comment]
Good point. I've removed the old one. Thanks.
